name: '🚀 Build and Push to ACR'

on:
  workflow_dispatch:
  push:
    branches:
      - GTMP-72

jobs:
  build-and-push:
    name: Build Docker Images and Push to ACR
    runs-on: ubuntu-latest
    environment: Integration

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }} --output none
          az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push User Service Docker Image to ACR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/user_service:${{ secrets.IMAGE_TAG }}
          context: ./user_service
          file: ./user_service/Dockerfile

      - name: Build and Push Auth Service Docker Image to ACR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/auth_service:${{ secrets.IMAGE_TAG }}
          context: ./auth_service
          file: ./auth_service/Dockerfile

      - name: Build and Push Email Service Docker Image to ACR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/email_service:${{ secrets.IMAGE_TAG }}
          context: ./email_service
          file: ./email_service/Dockerfile

  deploy-to-azure:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: Integration

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENV=production" >> $GITHUB_ENV
          else
            echo "ENV=local" >> $GITHUB_ENV
          fi

      - name: Authenticate to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }} --output none
          az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Deploy User Service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.USER_SERVICE_WEB_APP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/user_service:${{ secrets.IMAGE_TAG }}

      - name: Deploy Auth Service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AUTH_SERVICE_WEB_APP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/auth_service:${{ secrets.IMAGE_TAG }}

      - name: Deploy Email Service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.EMAIL_SERVICE_WEB_APP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/email_service:${{ secrets.IMAGE_TAG }}